# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/receitaws/',
                'doc_host': 'https://ronaldokun.github.io',
                'git_url': 'https://github.com/ronaldokun/receitaws/',
                'lib_path': 'receitaws'},
  'syms': { 'receitaws\\consultas': { 'receitaws\\consultas.Request': ('consultas.html#request', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.__init__': ('consultas.html#__init__', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.batch_request': ( 'consultas.html#batch_request',
                                                                                      'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.format_url': ('consultas.html#format_url', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.get_request': ('consultas.html#get_request', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.parse_json': ('consultas.html#parse_json', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.Request.query_ws': ('consultas.html#query_ws', 'receitaws\\consultas.py'),
                                      'receitaws\\consultas.request_from_file': ( 'consultas.html#request_from_file',
                                                                                  'receitaws\\consultas.py'),
                                      'receitaws\\consultas.save_request': ('consultas.html#save_request', 'receitaws\\consultas.py')}}}